Check which Python is being used

In [11]:
import sys
print(sys.executable)

/nas/ucb/sandytanwisuth/miniconda3/envs/voi/bin/python


Check which GPU is most available

In [12]:
import os
import subprocess

# Get GPU availability using nvidia-smi
gpu_query = "nvidia-smi --query-gpu=index,memory.free --format=csv,noheader,nounits"
gpu_info = subprocess.check_output(gpu_query, shell=True).decode("utf-8")

# Parse the output and find the GPU with the most free memory
gpu_list = [line.split(",") for line in gpu_info.strip().split("\n")]
gpu_list = [(int(idx), int(mem)) for idx, mem in gpu_list]  # Convert to int
best_gpu = sorted(gpu_list, key=lambda x: -x[1])[0][0]  # Choose GPU with max free memory

# Set the environment variable
os.environ["CUDA_VISIBLE_DEVICES"] = str(best_gpu)

print(f"Using GPU {best_gpu} with most available memory.")


Using GPU 1 with most available memory.


Import file reading

In [13]:
import numpy as np
import pickle

Files absolute paths

In [17]:
npz = "/nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250218/asymm_advantages/bl_ff_ippo_oc_default_20250218_102219_30/all_seeds_params.npz"
pkl = "/nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250219/cramped_room/bl_ff_ippo_oc_default_20250219_140909_30/all_seeds_params.pkl"
metrics = "/nas/ucb/sandytanwisuth/ser/value-of-intent/saved_models/20250219/cramped_room/adaptability_ff_ippo_oc_default_20250219_170633_30/metrics.npz"

Check content of metrics.npz

In [25]:
metrics_data = np.load(metrics)
print("Loaded data type:", type(metrics_data))
print("Keys in the .npz file:", metrics_data.files)

mean_reward = metrics_data['mean_reward']
print("Mean reward:", mean_reward)
print("Mean reward shape:", mean_reward.shape)

for key in metrics_data.files:
    print(f"\nKey: {key}")
    print(f"Data type: {metrics_data[key].dtype}")
    print(f"Shape: {metrics_data[key].shape}")
    print(f"Sample values:\n{metrics_data[key]}")


Loaded data type: <class 'numpy.lib.npyio.NpzFile'>
Keys in the .npz file: ['env_step', 'max_reward', 'mean_reward', 'min_reward', 'returned_episode', 'returned_episode_lengths', 'returned_episode_returns', 'shaped_reward', 'shaped_reward_annealed', 'std_reward', 'update_step']
Mean reward: [[0.18554688 0.16601562 0.10742188 ... 0.625      0.46875    0.78125   ]
 [0.16601562 0.22460938 0.20507812 ... 0.5859375  0.44921875 0.7714844 ]
 [0.17578125 0.17578125 0.18554688 ... 0.625      0.46875    0.76171875]
 ...
 [0.1953125  0.22460938 0.14648438 ... 0.49804688 0.44921875 0.625     ]
 [0.234375   0.25390625 0.1953125  ... 0.625      0.46875    0.78125   ]
 [0.21484375 0.20507812 0.15625    ... 0.625      0.47851562 0.76171875]]
Mean reward shape: (10, 24414)

Key: env_step
Data type: int32
Shape: (10, 24414)
Sample values:
[[    2048     4096     6144 ... 49995776 49997824 49999872]
 [    2048     4096     6144 ... 49995776 49997824 49999872]
 [    2048     4096     6144 ... 49995776 499

Check type and contents of pkl file

In [15]:
# Load the pickle file
with open(pkl, "rb") as f:
    data_pkl = pickle.load(f)

# Print the type of the loaded object
print("Loaded data type:", type(data_pkl))

# If it's a dictionary, print the keys
if isinstance(data_pkl, dict):
    print("Keys in the pickle file:", data_pkl.keys())

# Print a sample of the contents
for key, value in data_pkl.items():
    print(f"\nKey: {key} - Type: {type(value)}")
    print(value)  # Print the content (may need further processing based on its structure)

Loaded data type: <class 'dict'>
Keys in the pickle file: dict_keys(['seed_0', 'seed_1', 'seed_2', 'seed_3', 'seed_4', 'seed_5', 'seed_6', 'seed_7', 'seed_8', 'seed_9', 'seed_10', 'seed_11', 'seed_12', 'seed_13', 'seed_14', 'seed_15', 'seed_16', 'seed_17', 'seed_18', 'seed_19', 'seed_20', 'seed_21', 'seed_22', 'seed_23', 'seed_24', 'seed_25', 'seed_26', 'seed_27', 'seed_28', 'seed_29', 'seed_30', 'seed_31', 'seed_32', 'seed_33', 'seed_34', 'seed_35', 'seed_36', 'seed_37', 'seed_38', 'seed_39', 'seed_40', 'seed_41', 'seed_42', 'seed_43', 'seed_44', 'seed_45', 'seed_46', 'seed_47', 'seed_48', 'seed_49', 'seed_50', 'seed_51', 'seed_52', 'seed_53', 'seed_54', 'seed_55', 'seed_56', 'seed_57', 'seed_58', 'seed_59', 'seed_60', 'seed_61', 'seed_62', 'seed_63', 'seed_64', 'seed_65', 'seed_66', 'seed_67', 'seed_68', 'seed_69', 'seed_70', 'seed_71', 'seed_72', 'seed_73', 'seed_74', 'seed_75', 'seed_76', 'seed_77', 'seed_78', 'seed_79', 'seed_80', 'seed_81', 'seed_82', 'seed_83', 'seed_84', 'seed_

Check structure of the content of the pkl file

In [16]:
# If it's a dictionary, print the keys
if isinstance(data_pkl, dict):
    print("\nKeys in the pickle file:", list(data_pkl.keys()))

    # Print the type and shape of each value without printing all contents
    for key, value in data_pkl.items():
        print(f"\nKey: {key} - Type: {type(value)}", end="")
        if hasattr(value, "shape"):  # For numpy arrays, tensors, etc.
            print(f" - Shape: {value.shape}")
        elif isinstance(value, list):
            print(f" - Length: {len(value)}")
        elif isinstance(value, dict):
            print(f" - Subkeys: {list(value.keys())[:5]}")  # Print first 5 subkeys
        else:
            print()



Keys in the pickle file: ['seed_0', 'seed_1', 'seed_2', 'seed_3', 'seed_4', 'seed_5', 'seed_6', 'seed_7', 'seed_8', 'seed_9', 'seed_10', 'seed_11', 'seed_12', 'seed_13', 'seed_14', 'seed_15', 'seed_16', 'seed_17', 'seed_18', 'seed_19', 'seed_20', 'seed_21', 'seed_22', 'seed_23', 'seed_24', 'seed_25', 'seed_26', 'seed_27', 'seed_28', 'seed_29', 'seed_30', 'seed_31', 'seed_32', 'seed_33', 'seed_34', 'seed_35', 'seed_36', 'seed_37', 'seed_38', 'seed_39', 'seed_40', 'seed_41', 'seed_42', 'seed_43', 'seed_44', 'seed_45', 'seed_46', 'seed_47', 'seed_48', 'seed_49', 'seed_50', 'seed_51', 'seed_52', 'seed_53', 'seed_54', 'seed_55', 'seed_56', 'seed_57', 'seed_58', 'seed_59', 'seed_60', 'seed_61', 'seed_62', 'seed_63', 'seed_64', 'seed_65', 'seed_66', 'seed_67', 'seed_68', 'seed_69', 'seed_70', 'seed_71', 'seed_72', 'seed_73', 'seed_74', 'seed_75', 'seed_76', 'seed_77', 'seed_78', 'seed_79', 'seed_80', 'seed_81', 'seed_82', 'seed_83', 'seed_84', 'seed_85', 'seed_86', 'seed_87', 'seed_88', 'see